### PR TITLE
3rd attempt of utf-8 & i18n support

### PR DESCRIPTION
**Pull request by RealClearwave**
It's quite frustrating to tackle with git issues, but this time the problem should have been addressed.
`I18N` class is now optimzed as well.
Viper-based functions like `_bitmap_text` are hard to under stand as if they worked by magic. Maybe we can convert utf-8 chars to `font` type and call `_bitmap_text` to optimize speed in the future.

### CODE REVIEW

**Comment by echo-lalia** [comment]
Looks great! The conflicts were actually picked up by git this time, and I was able to easily resolve them and merge it into the [i18n-support](https://github.com/echo-lalia/MicroHydra/tree/i18n-support) branch (because I want to play around with some modifications before merging into main).

I agree that git issues can be really frustrating 😅 It's a really useful tool, but fixing a mistake is really confusing/difficult in my experience.

<br/>

> Viper-based functions like _bitmap_text are hard to under stand as if they worked by magic.

They're a lot easier to understand when you're the one who wrote them, haha. I wrote the `_bitmap_text` method in the current `st7789` module (from scratch, which was easier for me than modifying the previous author's text drawing methods, lol).  
Though, I realize now that (I *think*) the majority of the speed problems we're having are actually coming from the  `instant_show=True` element of the `utf8_text` method, which is updating the display every time a a utf8 character exists in a drawn string. I'll probably just remove this option for consistency with the other text methods.

**Comment by echo-lalia** [comment]
I think I might convert the translations into json strings.

I did some testing, and my original idea of trimming down the translation dictionaries into just the values needed actually used more memory than just using the larger/original dictionary directly. This makes sense, I guess, because the *code* that contains the original dictionary is still in memory, so trimming it down just means that we need to have two dictionaries in memory.

However, if the translation data is in a `const()` string, and then decoded using the json module, the original dictionary doesn't need to be in memory at all. Then if we trim that dictionary down, it uses significantly less memory.  
And, because the json module already needs to be imported by the `hydra.config` module, importing it elsewhere doesn't use any extra memory.

This might be a 'premature optimization', but I have spent so many hours fighting with this program over memory issues 😅 so I really wanna introduce these new features with as little memory usage as possible.

**Comment by RealClearwave** [comment]
custom_trans and to_lang are reserved just in case. You can delete them on your demand. 
btw I'm working on an app to connect multiple platforms (i.e. Android) with microhydra, maybe adding a 'Shell' module or REPL is a good idea😄

**Comment by echo-lalia** [comment]
I really like that idea! I saw that pull request, and then got distracted with this, haha.

**Comment by echo-lalia** [comment]
This pull request has been completed through 0a56e62f45d4268a6ee1f921bf4b0740b0da74b2 

I have merged your changes, resolved the conflicts, and modified some things for speed, memory and (hopefully) easier usability.

You're probably not gonna like the new `utf8_putc` method, as it's quite dense 😅 But, it is very fast, I think, and it is now being called automatically by `_bitmap_text` whenever a character is missing from the given font!

I also added the i18n support directly to `hydra.menu` and `hydra.popup` so that some of app code can be simplified.

**Pull request closed without merging**
